wandb_version: 1

_content:
  desc: null
  value:
    agent: ddpg_256
    agent_name: ddpg
    batch_size: '256'
    buffer_size: '1000000.0'
    env_name: bipedalwalker_easy
    exp_name: bipedalwalker_easy
    gamma: '0.99'
    lr: 5e-05
    model_path: default
    run_id: ???
    run_suffix: '0'
    save_logging: 'False'
    save_model: 'True'
    save_stats: 'True'
    save_video: 'True'
    seed: '1'
    seeds:
    - 1
    - 48
    - 128
    silent: 'False'
    target_rew: '250'
    tau: '0.005'
    testing: 'False'
    train_episodes: '10'
    use_wandb: 'True'
_flags_cache:
  desc: null
  value:
    struct: true
_metadata:
  desc: null
  value: 'ContainerMetadata(ref_type=typing.Any, object_type=<class ''dict''>, optional=True,
    key=None, flags={''struct'': True}, flags_root=False, resolver_cache=defaultdict(<class
    ''dict''>, {''now'': {(''%Y-%m-%d'',): ''2022-11-22'', (''%H-%M-%S'',): ''01-00-11''}}),
    key_type=typing.Any, element_type=typing.Any)'
_parent:
  desc: null
  value: null
_wandb:
  desc: null
  value:
    cli_version: 0.13.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1669071664.029532
    t:
      1:
      - 1
      - 50
      - 55
      2:
      - 1
      - 50
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.8.10
      5: 0.13.2
      8:
      - 5
