wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1669072808.959449
    t:
      1:
      - 1
      - 50
      - 55
      2:
      - 1
      - 50
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.8.10
      5: 0.13.2
      8:
      - 5
hd:
  desc: null
  value: 128
lr:
  desc: null
  value: 0.005
tau:
  desc: null
  value: 0.001
