wandb_version: 1

_content:
  desc: null
  value:
    agent: pg
    agent_name: pg
    batch_size: '100'
    buffer_size: '1000000.0'
    env_name: hopper_medium
    exp_name: hopper_medium
    gamma: '0.99'
    lr: '0.0003'
    model_path: /m/home/home3/32/floreya1/unix/RL/rl_course/project/part1/results/hopper_medium/model/pg_hopper_medium_params.pt
    run_id: '1668991267'
    run_suffix: '0'
    save_logging: 'False'
    save_model: 'True'
    save_stats: 'True'
    save_video: 'False'
    seed: '1'
    seeds:
    - 1
    - 48
    - 128
    silent: 'False'
    target_rew: '2000'
    testing: 'False'
    train_episodes: '5000'
    use_wandb: 'True'
_flags_cache:
  desc: null
  value:
    allow_objects: null
    convert: null
    readonly: null
    struct: true
_metadata:
  desc: null
  value: 'ContainerMetadata(ref_type=typing.Any, object_type=<class ''dict''>, optional=True,
    key=None, flags={''struct'': True}, flags_root=False, resolver_cache=defaultdict(<class
    ''dict''>, {''now'': {(''%Y-%m-%d'',): ''2022-11-21'', (''%H-%M-%S'',): ''02-41-06''}}),
    key_type=typing.Any, element_type=typing.Any)'
_parent:
  desc: null
  value: null
_wandb:
  desc: null
  value:
    cli_version: 0.13.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1668991269.583485
    t:
      1:
      - 1
      - 50
      - 55
      2:
      - 1
      - 50
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.8.10
      5: 0.13.2
      8:
      - 5
